# Generated by Django 4.0.4 on 2022-05-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deviceaccount_taskforceaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceAccount',
        ),
        migrations.DeleteModel(
            name='TaskForceAccount',
        ),
    ]
